### ISSUE TITLE
ipay88 has new version for their sdk

### ISSUE THREAD

**Issue by eshiply** [myussufz/react-native-ipay88-sdk#12]
I have tested the current sdk is not working now, as iPay88 has updated the sdk to V1.6.6, new parameters added for delegates and checkout function same to ios as well

**Comment by 15110011** [comment]
@eshiply i have installed your fork, and when i run yarn android, it got this problem
 What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find :IpayHostedStandard_MY_SDK_Aar_08072019:.
     Required by:
         project :app > project :eshiply-ipay88

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/Users/ducanh/Desktop/customer-mobile-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/ducanh/Desktop/customer-mobile-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/ducanh/Desktop/customer-mobile-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by christiandave090697** [comment]
Hello, I'm having the same error as I need to use the latest sdk version of ipay88, is there a solution?
